visuals/fidget: use submodule for notification group overrides
NotAShelf/nvf pull request #272
Opened 2024-04-28 20:08 UTC by FrothyMarrow

Changes `display.overrides` to use `submodule` instead of `anything` for better eval time checks.

2024-04-28 20:23 UTC, NotAShelf approved these changes
LGTM. Is this tested?

2024-04-29 01:26 UTC, FrothyMarrow commented
> LGTM. Is this tested?

It was tested, but I was using the wrong defaults. Fixed that and added the changelog entry, should be good to go now.

2024-04-29 12:22 UTC, NotAShelf requested changes
a few changes required

also rebase around main please

2024-04-29 12:22 UTC, NotAShelf commented on modules/plugins/visuals/fidget/fidget.nix
> +              if default configuration is not defined, the following defaults are used:
new line, capitalize first letter.

2024-04-29 12:22 UTC, NotAShelf commented on modules/plugins/visuals/fidget/fidget.nix
> +                    for more information on the function signature, see:
new line, capitalize first letter.

include as a note:

```
::: {.note}
some note here
:::
```

2024-05-02 03:21 UTC, NotAShelf approved these changes
LGTM, thanks

2024-05-02 03:21 UTC, merged