lib: do not filter out empty attrs in toLuaObject
NotAShelf/nvf pull request #289
Opened 2024-05-12 01:20 UTC by horriblename

there is a single use of `__empty` in the codebase, I need to double check what it's doing before I remove it

2024-05-18 13:10 UTC, NotAShelf submitted a review, later dismissed
LGTM

2024-05-18 13:11 UTC, NotAShelf commented
can be merged once @FrothyMarrow also approves

2024-05-18 23:50 UTC, FrothyMarrow reviewed
Add a warning for the users in case they are using `__empty`.

2024-05-21 11:05 UTC, NotAShelf commented on lib/lua.nix
> +        lib.warn ''
Inherit `warn` from (lib.trivial) on top. We do not use aliases.

2024-05-21 11:05 UTC, NotAShelf requested changes
minor nit, LGTM otherwise

2024-05-21 11:10 UTC, NotAShelf approved these changes

2024-05-21 11:16 UTC, merged