neorg: init
NotAShelf/nvf pull request #413
Opened 2024-10-09 06:51 UTC by Soliprem

Adds [Neorg](github.com/nvim-neorg/neorg) support under vim.notes.neorg.

Neorg depends on new dependencies:
- [lua-utils.nvim](github.com/nvim-neorg/lua-utils.nvim)
- [pathlib.nvim](github.com/pysan3/pathlib.nvim)
- [neorg-telescope](github.com/nvim-neorg/neorg-telescope)

## Sanity Checking

[editorconfig]: https://editorconfig.org
[changelog]: https://github.com/NotAShelf/nvf/tree/main/docs/release-notes

- [X] I have updated the [changelog] as per my changes.
- [X] I have tested, and self-reviewed my code.
- Style and consistency
  - [X] I ran **Alejandra** to format my code (`nix fmt`).
  - [X] My code conforms to the [editorconfig] configuration of the project.
  - [X] My changes are consistent with the rest of the codebase.
- If new changes are particularly complex:
  - [ ] My code includes comments in particularly complex areas
  - [ ] I have added a section in the manual.
  - [ ] _(For breaking changes)_ I have included a migration guide.
- Package(s) built:
  - [X] `.#nix` (default package)
  - [X] `.#maximal`
  - [X] `.#docs-html`
- Tested on platform(s)
  - [X] `x86_64-linux`
  - [ ] `aarch64-linux`
  - [ ] `x86_64-darwin`
  - [ ] `aarch64-darwin`

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-14 21:31 UTC, NotAShelf requested changes
Small changes, LGTM otherwise.

2024-10-14 21:31 UTC, NotAShelf commented on modules/plugins/notes/neorg/config.nix
> +
```suggestion

```

2024-10-14 21:31 UTC, NotAShelf commented on modules/plugins/notes/neorg/neorg.nix
> +    enable = mkEnableOption "neorg: Neovim plugin for Neorg";
This can be more descriptive than "plugin: neovim plugin for plugin".

2024-10-14 21:31 UTC, NotAShelf commented on modules/plugins/notes/neorg/neorg.nix
> +              enable = mkEnableOption "A wrapper to interface with several different completion engines.";
`mkEnableOption` prepends "Whether to enable" before the given string. You may remove the article.

2024-10-14 21:32 UTC, NotAShelf commented
You'll also need to resolve the merge conflict.

2024-10-15 09:38 UTC, NotAShelf commented on modules/plugins/notes/neorg/neorg.nix
> +              enable = mkEnableOption "Wrapper to interface with several different completion engines.";
```suggestion
              enable = mkEnableOption "wrapper to interface with several different completion engines.";
```

2024-10-15 09:39 UTC, NotAShelf commented on modules/plugins/notes/neorg/neorg.nix
> +                  default = [];
Could this be given a `description` and ideally also an `example`?

2024-10-15 09:39 UTC, NotAShelf requested changes
Last two changes, good to go afterwards.

2024-10-15 12:48 UTC, NotAShelf commented
Needs formatting and .editorconfig checks to succeed.

2024-10-15 14:14 UTC, Soliprem commented
should be fixed now

2024-10-15 15:30 UTC, NotAShelf approved these changes

2024-10-15 15:31 UTC, merged