languages/julia: init
NotAShelf/nvf pull request #431
Opened 2024-10-31 13:46 UTC by diniamo

## Sanity Checking

[editorconfig]: https://editorconfig.org
[changelog]: https://github.com/NotAShelf/nvf/tree/main/docs/release-notes

- [x] I have updated the [changelog] as per my changes.
- [x] I have tested, and self-reviewed my code.
- Style and consistency
  - [x] I ran **Alejandra** to format my code (`nix fmt`).
  - [x] My code conforms to the [editorconfig] configuration of the project.
  - [x] My changes are consistent with the rest of the codebase.
- If new changes are particularly complex:
  - [x] My code includes comments in particularly complex areas
  - [ ] I have added a section in the manual.
  - [ ] _(For breaking changes)_ I have included a migration guide.
- Package(s) built:
  - [ ] `.#nix` (default package)
  - [ ] `.#maximal`
  - [ ] `.#docs-html`
- Tested on platform(s)
  - [x] `x86_64-linux`
  - [ ] `aarch64-linux`
  - [ ] `x86_64-darwin`
  - [ ] `aarch64-darwin`

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-31 13:56 UTC, horriblename reviewed
LGTM aside from the tiny nitpick

2024-10-31 13:56 UTC, horriblename commented on docs/release-notes/rl-0.7.md
> +  to provide only the LSP server.
This should probably be in the `vim.language.julia.lsp.enable` option description

2024-11-01 21:37 UTC, NotAShelf commented on modules/plugins/languages/julia.nix
> +            in PATH (set it to `null`), and add the `LanguageServer` package to
```suggestion
            in {env}`PATH` (set it to `null`), and add the `LanguageServer` package to
```

2024-11-01 21:37 UTC, NotAShelf commented on modules/plugins/languages/julia.nix
> +            Julia LSP server package, null to use the Julia binary in PATH, or
```suggestion
            Julia LSP server package, `null` to use the Julia binary in {env}`PATH`, or
```

For consistency: `null` is inline code in previous desc, but not here.

2024-11-01 21:39 UTC, NotAShelf requested changes
Two quick changes for consistency.

Not a deal-breaker, but I'd appreciate it if the order of `mkOption` args were 

```nix
{
  type = ...
  default = ...
  description = ...
}

2024-11-02 23:49 UTC, NotAShelf approved these changes

2024-11-02 23:49 UTC, merged