filetree/nvim-tree: Open on directory
NotAShelf/nvf pull request #462
Opened 2024-11-12 02:29 UTC by DamitusThyYeetus123

When nvim-tree is enabled, opening nvim with a directory opens nvim-tree in that directory, and cds to the directory.

## Sanity Checking

[editorconfig]: https://editorconfig.org
[changelog]: https://github.com/NotAShelf/nvf/tree/main/docs/release-notes

- [ ] I have updated the [changelog] as per my changes.
- [x] I have tested, and self-reviewed my code.
- Style and consistency
  - [x] I ran **Alejandra** to format my code (`nix fmt`).
  - [x] My code conforms to the [editorconfig] configuration of the project.
  - [x] My changes are consistent with the rest of the codebase.
- If new changes are particularly complex:
  - [ ] My code includes comments in particularly complex areas
  - [ ] I have added a section in the manual.
  - [ ] _(For breaking changes)_ I have included a migration guide.
- Package(s) built:
  - [x] `.#nix` (default package)
  - [x] `.#maximal`
  - [ ] `.#docs-html`
- Tested on platform(s)
  - [x] `x86_64-linux`
  - [ ] `aarch64-linux`
  - [ ] `x86_64-darwin`
  - [ ] `aarch64-darwin`

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-15 06:47 UTC, NotAShelf commented
Opening a directory with `vim .` should already open said directory with nvim-tree. I think this might be related to LazyLoading since we currently have a similar issue with neo-tree.

2024-11-15 06:49 UTC, diniamo commented
#446 should fix this too.

2024-11-15 06:50 UTC, DamitusThyYeetus123 commented
This feature was removed from nvimTree and should be added externally as seen here https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup

2024-11-15 06:52 UTC, diniamo commented
it's still going to have conflicts with that PR, so you have to at least rebase on it.

2024-11-15 06:54 UTC, DamitusThyYeetus123 commented
Is that PR not ready for commit yet?

2024-12-02 23:35 UTC, DamitusThyYeetus123 commented
#446 did not fix, will rebase and fix up now.

2024-12-02 23:43 UTC, DamitusThyYeetus123 commented
Rebased, no fixes needed

2024-12-03 00:30 UTC, horriblename requested changes
LGTM, except the unnecessary space

2024-12-03 00:30 UTC, horriblename commented on modules/plugins/filetree/nvimtree/config.nix
> +              end
```suggestion
              end
```

no space at end of line pls

2024-12-03 00:32 UTC, horriblename commented
(waiting for CI to finish)

2024-12-03 22:34 UTC, DamitusThyYeetus123 commented
whoops lemme fix up formatting

2024-12-03 23:04 UTC, NotAShelf commented on modules/plugins/filetree/nvimtree/config.nix
> +                local directory = vim.fn.isdirectory(data.file) == 1
```suggestion
              -- buffer is a directory
              local directory = vim.fn.isdirectory(data.file) == 1
```

2024-12-23 03:11 UTC, horriblename approved these changes

2024-12-23 08:56 UTC, merged