neovim: gradually deprecate shorthand `vim.*` aliases to `vim.options` and `vim.globals`
NotAShelf/nvf pull request #480
Opened 2024-12-02 21:57 UTC by NotAShelf

Slowly deprecates top-level options that used to set Neovim's `vim.opt` options in favor of `vim.options` and `vim.globals` module options.

2024-12-02 23:16 UTC, horriblename commented on modules/wrapper/rc/options.nix
> +            type = bool;
should be `either bool str`

"auto" and "yes:3" aren't exactly booleans

2025-01-10 07:59 UTC, merged

2025-01-10 08:05 UTC, diniamo requested changes

2025-01-10 08:05 UTC, diniamo commented on modules/wrapper/rc/options.nix
> +          };
Please just have it be a string, and remove the toVimBool function

2025-01-10 08:05 UTC, diniamo commented on modules/wrapper/rc/options.nix
> +      example = literalExpression ''''${builtins.readFile ./my-lua-config-pre.lua}'';
```suggestion
      example = literalExpression "\${builtins.readFile ./my-lua-config-pre.lua}";
```

2025-01-10 08:05 UTC, diniamo commented on modules/neovim/init/basic.nix
> +      })
We should just deprecate these too, no point in abstractions

2025-01-10 08:07 UTC, NotAShelf commented on modules/neovim/init/basic.nix
> +      })
I'm not keen on aggressive deprecations outside the 'release cycle.' We can consider fully deprecating those options in the 0.8 branchout.